# Generated by Django 5.0.7 on 2024-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('user_phone', models.CharField(max_length=15, null=True)),
                ('code', models.PositiveIntegerField()),
            ],
        ),
    ]
