# Generated by Django 5.0.7 on 2024-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_purchases_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_register',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
