# Generated by Django 5.0.7 on 2024-09-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_register_date_register_alter_register_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_password',
        ),
    ]
